---
tags: []
layout: input_bottom
editor: code
type: interactive
extra_visible: false
language: bash
manual_evaluation: false
choices: []
goal:
  kind: query_passes
  query: git remote show origin -v | grep -oq http://otra-pc/foo/bar
name: Repositorios remotos
