---
tags: []
layout: input_bottom
editor: code
type: interactive
extra_visible: false
language: bash
manual_evaluation: false
choices: []
goal:
  kind: last_query_equals
  value: git remote add origin http://otra-pc/foo/bar
name: Repositorios remotos
