---
tags: []
layout: input_bottom
editor: code
type: interactive
extra_visible: false
language: bash
manual_evaluation: false
choices: []
goal:
  kind: query_outputs
  query: git remote -v | grep origin | grep http | grep push
  output: origin  http://otra-pc/foo/bar (push)
name: Repositorios remotos
