---
tags: []
layout: input_bottom
editor: code
type: interactive
extra_visible: false
language: bash
manual_evaluation: false
choices: []
goal:
  kind: query_passes
  query: git remote show origin -n | grep http://otra-pc/foo/bar -oq
name: Repositorios remotos
