---
tags: []
layout: input_bottom
editor: code
type: interactive
extra_visible: false
language: bash
manual_evaluation: false
choices: []
goal:
  kind: query_outputs
  query: git remote show origin -n | grep remote
  output: "* remote origin"
name: Repositorios remotos
