---
tags: []
layout: input_bottom
editor: code
type: interactive
extra_visible: false
language: bash
manual_evaluation: false
choices: []
goal:
  kind: last_query_outputs
  output: El repositorio se actualizó correctamente
name: Subiendo los cambios
