---
tags: []
layout: input_bottom
editor: code
type: interactive
extra_visible: false
manual_evaluation: false
choices: []
goal:
  kind: last_query_outputs
  output: No tenés permisos para actualizar el repositorio en Github
